### ISSUE TITLE
Module initialization proposal

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#136]
##### General

- Modules are holders for static functions and values (and variables), serving as a replacement for global/free-standing/static members.
- Modules are instances, they have vtables, can be passed around as values and may extend classes and support traits.

##### Initialization

- Initialization a module means initializing its members.
- Initialized modules and their values/variables are never garbage collected.
- Modules should be initialized on their first use, such that loading some library does not require initializing and retaining arbitrary stuff that is kept forever, if it's not even used.

#### Requirements

- Modules should only be initialized on first access.
- Modules should only ever be initialized once.
- Module members (except variables) should be able to be treated as effectively constant from an optimization POV.

#### Problems

- Guarding every use of a module with a check whether it needs to be initialized is undesirable, because that check would exist for the rest of the application’s run at every use-site (imagine the module is accessed from within a loop, as in the example below).
- Guarding every use of a module with a check is undesirable because it acts as an optimization/inlining barrier and would require these techniques to be more sophisticated to optimize through modules.

```
module Foo {
  let bar: String = "baz";
  fun qux(x: Int) -> Int = x * 2;
  var gof: Double = 123.45;
}

while condition {
  // Foo members (bar, gof) initialized at first use of Foo:
  somethingWith(Foo.bar); 
}
```

#### Idea

Instead of emitting code that checks for initialization at every use-site, let the uninitialized module access the zero page, trap it, trigger the initialization and resume execution.

A page fault is massively slower than a null-check, but the difference is that the page fault happens at most once and does not add code to every use-site, while the null check would need to be done at every access.

---

Additional thought: Pretty much all modules of the standard library should be immutable, such that instead of shipping the standard library as source code or bytecode, it should be possible to memory-map an fully initialized image of the standard library. The module design should enable this.

**Comment by dinfuehr** [comment]
I've recently removed all the signal handling from Dora - this made it much easier to support Windows (current state: all tests succeed, however there is still a problem left that I need to investigate. Then we can enable Windows in the CI as well). That's why I am a bit hesitant to reintroduce signal handling again. If we do this, we should also support Windows.

Personally I don't think the explicit checks would be a problem: 1) the compiler (even baseline) can always omit the checks if it sees that a global variable was already initialized - not unlikely with lazy compilation 2) that loop above should be recompiled by the optimizing compiler later when it is hot.

Also with signal handling each module probably needs at least 4K in size. That said, whether we use signal handling or an explicit check is an implementation detail and can be decided later.

Do we also initialize a module when a function in it was called? This is what I would expect would happen, but you didn't mention it so far. This might need to generate additional code. Generally I think this is all very similar to the Java class-loading mechanism.

Also not sure how this "object" would look like. It might have different requirements than "regular" objects and should probably go to the perm-space.

I don't think this solves the problem of dependencies between global variables (e.g. someFunction using y internally) in the same module:

```
module xyz { var x = someFunction(); var y = anotherFunction(); ... }
```

That's why I would prefer to do this check on a per-variable base, this would solve this nicely.

**Comment by soc** [comment]
> I don't think the explicit checks would be a problem [...]

Agreed on using null checks (I remembered that some JVM languages suffered from poor performance initializing modules this way, but it's certainly possible that I misremember the details, or that the causes don't apply to us).

> Do we also initialize a module when a function in it was called?

I'd expect a module `A` to be initialized whenever it is mentioned itself, or something in it.

To be clear, everything I wrote is only relevant for "capital-letter" modules `X`, not for the "namespacing" modules `x`.

Small-letter modules should only contain "big declarations" classes, structs, impls, modules, but no "small declarations" (`let`, `var`, maybe even `fun`).

I'll reply to the rest tomorrow!

**Comment by soc** [comment]
Basically my idea is:

```
module time // lowercase module, can be nested: module foo.bar.qux

// class, module, trait, impl ok here in lowercase modules:

class LocalTime(hours: Int, minutes: Int, seconds: Int) {
  // fun, let, var ok here
  fun toString() -> String = ...
  ...
}

module LocalTime extends ... { // uppercase module
  // fun, let, var ok here
  fun parse(value: String) -> LocalTime = ...
  let midnight: LocalTime = ...
  ...
}

trait Temporal {
  ...
}

impl Stringable for LocalTime {
  ...
}

// NO let, var in lowercase modules
// Maybe fun is ok? (Nothing preventing it from the technical side, but
// for consistency with disallowing let, var it might make sense to forbid.)  
```

- Modules that begin with a lowercase letter are intended for namespacing, they disallow everything that would require allocation/initialization: `let`, `var`, extending classes, etc.

- Modules that begin with a uppercase letter are intended as holders of data and as singleton instances that can be passed around.

Initialization-wise the idea for uppercase modules is that they follow the same rules as initializing class instances: They are initialized from top to bottom, with parent-classes initializing first.

The coarse-grained initialization (compared to initializing individual fields individually) comes from my experience that:
- coming up with "smarter" initialization approaches pretty much locks one in into that particular algorithm forever, because people start rely on it, and it's really hard to prove that a new-and-improved algorithm is a subset of the existing behavior.
- it doesn't really help to save people from initialization problems – people will just write more complex initialization behavior.
- having it behave identical to instance initialization makes things easier to understand as there is only one set of rules, not two different ones.
- while individually initializing `let`s and `var`s can work reasonably fine for reference types (just use `null` for "uninitialized"), it requires additional bitfields on the side to keep track of what's initialized and what isn't. This again opens up the problem of having to choose between threadsafe initialization and fast initialization. From Scala the lesson was that in 90% of the cases nobody needs threadsafe initialization, but the last 10% `let`s/`var`s that need it will cause annoying issues (hard to debug + people actually having to make a choice).
