### ISSUE TITLE
Report file names on errors

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#24]
One very important idea would be to report file names for errors.

In the past this wasn't necessary since there was only one file possible.

**Comment by dinfuehr** [comment]
Here are some action points that could be done when working on this:

- [ ] Read source file into string and then parse/lex String instead of the File
- [ ] Keep all file strings in a table and use an index to identify a file
- [ ] Move file into `Position`
- [ ] `Position` then stores `file`, `line` and `column`. Let's have a location map and make `Position` an index into that map. `Position` should than be defined as `Position(u32)`, this should save some memory and allow for faster copying
- [ ] Keep indices of start of line numbers in a table, we can use this to print the full line in source code to highlight errors

**Comment by soc** [comment]
@dinfuehr I think you did a lot of work here recently, do you feel this has been resolved for good?

**Comment by soc** [comment]
Closing this, feel free to reopen, @dinfuehr!
