### ISSUE TITLE
Get rid of procedure syntax

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#41]
Currently we have two different kinds of functions:

    fun function(...): Something { ... }

and

    fun procedure() { ... }

I propose removing the second syntax ("procedure syntax") in favor of

    fun procedure(): Unit { ... }

for multiple reasons:

- It makes the language more regular.
- I think it discourages programming without side-effects if side-effecting functions get better syntax than functions without side-effects.

**Comment by dinfuehr** [comment]
Not sure I agree with this: This shouldn't really be surprising coming from many other programming languages (e.g. Rust or Swift). I guess your main point is to discourage functions with side-effects. Not sure it helps that much since it only makes the definition more tedious to type and longer to read. It certainly doesn't discourage side-effects in functions with return values for example.

**Comment by soc** [comment]
I'd say my main point is consistency. it feels very weird (at least to me) that there is one syntax for functions of all types, except for functions with one "special" type, which gets a different syntax.

I agree on your point that dropping procedure syntax doesn't rule out side-effects in functions, but in my experience it helps nudging people into the right direction.

**Comment by soc** [comment]
If one takes `fun procedure() { ... }` at face value, it could mean all kinds of things to the uninitiated reader– the return type is inferred, it returns `Object`, it's dynamically typed etc. Having procedures follow the same rules as all other methods solves this issue.
