### ISSUE TITLE
Drop nil from the language

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#62]
This proposal is based on the idea that we can remove and replace `nil`, which is untyped, can inhabit every reference type and therefore fail in unexpected places, with something safer.

###  Progress

- [x] Replace nil-producing array creation with alternatives.
- [x] Have an `Option` type.
- [ ] Runtime can represent options as references|nullpointer.
- [ ] Replace remaining nil-using code with alternatives.

---

The fundamental consideration is that it is much easier to disallow the entry points through which `nil`s can occur – than to allow them, and then try and make them safe and put the genie back into the bottle.

There are two ways to get a `nil` in Dora – either explicitly or implicitly. Let's dissect these cases separately:

### explicit nils

Explicit nils often occur as initial assignments to `var` in the source code and are later reassigned. Example:

```
var str: String = nil;
if condition {
  str = "foo";
} else {
  str = "bar";
}
```

Disallowing `nil` in such cases would require initializing them either to some "dummy" value (not that good) or to support if-expressions, such that the code above could be written as:

```
let str: String = if condition {
    "foo";
  } else {
    "bar";
  }
```

Note that this would enable us to also replace `var`s with `let`s in cases, where the binding was only mutable to allow initialization.

### implicit nils

Implict nils arise from creating arrays of reference types with a bare length, like in this example:

```
let array = Array[String](3);
```

Here my proposal is to further extend our factory functions (`arrayEmpty`, `arrayFill`) and make array construction via a bare length only accessible to these factory functions, such that every case where a user might want to create an unsafe, uninitialized array is catered by a safe function instead.

This means having at least (names are ad-hoc):

- `fun arrayEmpty[T]() -> Array[T]` as a replacement for code like `let array = Array[...](0)`
- `fun arrayFill<T>(len: Int, value: T) -> Array[T]` as a replacement for code like `let array = Array[...](2); array(0) = ...; array(1) = ...`
- `fun arrayGenerate[T](len: Int, func: Int -> T) -> Array[T]` as a replacement for code like `let array = Array[...](2); someInitFunction(array);`
- `fun arrayDefault[T : Default](len: Int) -> Array[T]` as a replacement for getting arrays that are initialized to the `T::default` for that type. (Probably `0`, `0.0` for numbers, `""` strings (?) and user-definable for their own types.)
- `fun arrayZero[T : Zero](len: Int) -> Array[T]`, where `Zero` is a built-in trait that is only implemented by primitives and `Option` and whose core difference to `Default` is that unlike the latter no function to initialize the individual needs to be run, it's enough to allocate zeroed memory.

If we assume that `Option` is a struct and we gain a "free" `Option[T]` for every `T` where `T` is not a struct (as a result of dropping `nil`, because we can represent the first layer of `Option` as a null pointer), then the last function gets to shine:

```
class Foo(let bar: Int) {} // Foo does not impl Zero!
// But struct Option does, such that Option::zero == None

// an array just as dense as a Array[Foo] when Dora had nils, because None == <null pointer>:
val probablySomeFoos = arrayZero[Option[Foo]](5);
```

**Comment by dinfuehr** [comment]
Sounds good!

**Comment by dinfuehr** [comment]
I think removing nil became recently feasible in Dora. Thanks to @soc, we now have the [Option](https://github.com/dinfuehr/dora/blob/master/stdlib/Option.dora) class and the [arrayDefault](https://github.com/dinfuehr/dora/blob/master/stdlib/Array.dora#L56)-function (although it's called arrayNew but feel free to change it). I don't think we need the lambda-version right now since we have the `Vec` class as well.

I guess what is left is to simply require initializers for fields and to make `Array[T](length: Int)` private to stdlib. The latter one could be "solved" for now by simply treating the array constructor as internal. Later when functions can be private to a module it is straight-forward to rectify this.

Apart from that I suppose we only need to remove nil from tests and test/benchmark programs - and then removing nil-support completely from the language.

**Comment by soc** [comment]
Very exciting progress, I updated the description above to the new syntax and the rough semantics of the existing code for `Default`; also added `arrayZero` as a more limited, but more lightweight alternative for types where no custom initialization code needs to be run.

**Comment by dinfuehr** [comment]
Not sure we need `arrayZero` for avoiding initialising twice. I think the optimizing compiler or runtime should be able to detect this and optimize it away. We need that anyways since classes like `Vec[T]` can't use `arrayZero` since they operate on all possible types.

**Comment by soc** [comment]
From my perspective it's not about initializing twice, it's avoiding initialization altogether:

Allocating zeroed memory for those types implementing `Zero` means that the type is properly initialized, but not every type can implement `Zero`.

`Default` is different in that every type could implement it.

For example, `String` could support `Default` with a default value of `""`; `arrayDefault[String](10)` would mean that the `defaultValue` would be computed 10 times.

Assuming that `String` is a reference type, it wouldn't be able to support `Zero` though; the closest thing would be an `Option[String]`; in the case of `arrayZero[Option[String]](10)` no initialization code would need to be run at all, as `zeroValue` of `Option` would be `None`, which in turn is represented as a null pointer.

**Comment by dinfuehr** [comment]
The array constructor `Array[T](len)` always initializes (zeros) the allocated memory. So we always initialize memory at least once. I think this is the step where we count differently.

With `arrayFill` or `arrayDefault` we then initialize the array with some value a second time. `arrayZero` would guarantee a single initialization, but I think this is something we might also be able to achieve with the compiler/runtime without providing a special function.

My argument is that many potential users can't use `arrayZero` anyways since e.g. `T` might not implement the `Zero` trait (e.g. `Vec`). That's why we should try to avoid the second initialization for `arrayFill` and `arrayDefault` if possible as well. As soon as we have that, there would be no use for `arrayZero` anymore.

**Comment by soc** [comment]
Is this done for good, @dinfuehr with your recent commits? :-)

**Comment by dinfuehr** [comment]
I think it's mostly done, there might be some cleanup needed but I guess we can close this already.
